Electric Vehicle Routing Problem: RandomSearchOptimizer Class Reference
RandomSearchOptimizer Class Reference
#include <RandomSearchOptimizer.h>
Public Member Functions
RandomSearchOptimizer (const EVRP_Data &data)
void Optimize (vector< int > &bestTour, float &bestDistance) override
Generate NUM_GENERATIONS * SOLUTIONS_PER_GENERATION random solutions, saving the best from each generation. We use random generation to generate SOLUTIONS_PER_GENERATION purely random solutions. We save the best one, and do this NUM_GENERATIONS times. By the end, we will have NUM_GENERATIONS "good" solutions. This could be used as a good seed for other algorithms that start with an initial population.
Public Member Functions inherited from AlgorithmBase
AlgorithmBase ()
AlgorithmBase (const string &algorithm_name, const EVRP_Data &data)
virtual ~AlgorithmBase ()
string GetName ()
vector< string > GetHyperParameters ()
Additional Inherited Members
Protected Member Functions inherited from AlgorithmBase
void SetHyperParameters (const vector< string > &params)
Static Protected Member Functions inherited from AlgorithmBase
static void PrintIfTheTimeIsRight (const string &alg, const int &current, const int &max)
Protected Attributes inherited from AlgorithmBase
EVRP_Data problem_data
Vehicle * vehicle
Constructor & Destructor Documentation
RandomSearchOptimizer()
RandomSearchOptimizer::RandomSearchOptimizer (const EVRP_Data & data) inline
                                                 :
        AlgorithmBase("Random Search", data)
    {
        vector<string> hyper_parameters;
        hyper_parameters.push_back(string("Solutions per Generation: ") + to_string(SOLUTIONS_PER_GENERATION));
        hyper_parameters.push_back(string("Number of Best Solutions: ") + to_string(NUM_GENERATIONS));
        SetHyperParameters(hyper_parameters);
    }
References AlgorithmBase::hyper_parameters, NUM_GENERATIONS, AlgorithmBase::SetHyperParameters(), and SOLUTIONS_PER_GENERATION.
Member Function Documentation
Optimize()
void RandomSearchOptimizer::Optimize (vector< int > & bestTour, float & bestDistance) override virtual
Generate NUM_GENERATIONS * SOLUTIONS_PER_GENERATION random solutions, saving the best from each generation. We use random generation to generate SOLUTIONS_PER_GENERATION purely random solutions. We save the best one, and do this NUM_GENERATIONS times. By the end, we will have NUM_GENERATIONS "good" solutions. This could be used as a good seed for other algorithms that start with an initial population.
Parameters
bestTour The best complete tour through all the customer nodes
bestDistance The distance of the best tour
Implements AlgorithmBase.
{
    const int tourSize = static_cast<int>(problem_data.nodes.size()) - problem_data.customerStartIndex;
    map<vector<int>, float> bestSolutions;
    for (int i = 0; i < NUM_GENERATIONS; i++)
    {
        vector<int> _bestTour;
        float _bestDistance = numeric_limits<float>::max();
        //PrintIfTheTimeIsRight("Random Search", i, NUM_GENERATIONS);
        for (int j = 0; j < SOLUTIONS_PER_GENERATION; j++)
        {
            vector<int> tour = HelperFunctions::GenerateRandomTour(problem_data.customerStartIndex, tourSize);
            const float tourDistance = vehicle->SimulateDrive(tour, false);
            if (tourDistance < _bestDistance)
            {
                _bestDistance = tourDistance;
                _bestTour = tour;
            }
        }
        bestSolutions.emplace(_bestTour, _bestDistance);
    }
    bestDistance = numeric_limits<float>::max();
    for (const auto &iter : bestSolutions)
    {
        if (iter.second < bestDistance)
        {
            bestTour = iter.first;
            bestDistance = iter.second;
        }
    }
    /*
    cout << "Best tour: ";
    HelperFunctions::PrintTour(bestTour);
    cout << "The best tour has distance breakdown: " << vehicle->SimulateDrive(bestTour, true) << endl;
    cout << "Number of \"best\" solutions in solution map: " << bestSolutions.size() << endl;
    for (auto iter : bestSolutions)
    {
        HelperFunctions::PrintTour(iter.first);
        cout << "\t with distance " << iter.second << endl;
        cout << "---------------------------------------" << endl;
    }
    */
}
References EVRP_Data::customerStartIndex, HelperFunctions::GenerateRandomTour(), EVRP_Data::nodes, NUM_GENERATIONS, AlgorithmBase::problem_data, Vehicle::SimulateDrive(), SOLUTIONS_PER_GENERATION, and AlgorithmBase::vehicle.
The documentation for this class was generated from the following files:
EVRP/Algorithms/RandomSearch/RandomSearchOptimizer.h
EVRP/Algorithms/RandomSearch/RandomSearchOptimizer.cpp