Electric Vehicle Routing Problem: Vehicle Class Reference
Vehicle Class Reference
#include <Vehicle.h>
Public Member Functions
Vehicle (const vector< Node > &nodes, const float battery, const int inventory, const float batteryRate)
void ResetVehicle ()
float SimulateDrive (const vector< int > &desiredRoute, bool verbose=false)
Private Member Functions
int GetClosestChargingStationToNode (const Node &node) const
bool CanGetToNextCustomerSafely (const Node &from, const Node &to) const
float BatteryCost (const Node &node1, const Node &node2) const
float CalculateFullRouteDistance (const vector< int > &trueRoute, bool verbose=false) const
vector< Node > astar_pathfinding (const vector< Node > &graph, const Node &start, const Node &end)
Private Attributes
vector< Node > _nodes
float _battery
int _inventory
float _batteryRate
float currentBatteryCapacity
float maxBatteryCapacity
int currentInventoryCapacity
int maxInventoryCapacity
float batteryConsumptionRate
Constructor & Destructor Documentation
Vehicle()
Vehicle::Vehicle (const vector< Node > & nodes, const float battery, const int inventory, const float batteryRate) inline
Vehicle constructor.
Sets internal variables used in the calculation and simulation of driving the tour, then calls ResetVehicle to make sure everything is initialized properly
Parameters
nodes All nodes in the EVRP graph
battery The maximum capacity of the EV battery
inventory The maximum size of the vehicle's carrying capacity
batteryRate The rate in which the battery discharges over distance
    {
        _nodes = nodes;
        _battery = battery;
        _inventory = inventory;
        _batteryRate = batteryRate;
        ResetVehicle();
    }
References _battery, _batteryRate, _inventory, _nodes, and ResetVehicle().
Member Function Documentation
astar_pathfinding()
vector< Node > Vehicle::astar_pathfinding (const vector< Node > & graph, const Node & start, const Node & end) private
BatteryCost()
float Vehicle::BatteryCost (const Node & node1, const Node & node2) const private
Calculates the battery cost between two nodes, factoring in the battery consumption rate
Parameters
node1 The first node
node2 The second node
Returns
The battery cost between both nodes.
{
    return HelperFunctions::CalculateInterNodeDistance(node1, node2) * batteryConsumptionRate;
}
References batteryConsumptionRate, and HelperFunctions::CalculateInterNodeDistance().
CalculateFullRouteDistance()
float Vehicle::CalculateFullRouteDistance (const vector< int > & trueRoute, bool verbose = false) const private
Calculates the inter-node distance between each node in the true tour, once the true tour has been determined by the SimulateDrive function
Parameters
trueRoute The true route as determined by the SimulateDrive function
verbose False by default, but useful for debugging the distance calculations
Returns
Returns the true distance of the found route.
{
    float dist = 0.f;
    //iterate from node 1 in the true route to the end of the route
    for (size_t i = 1; i < trueRoute.size(); i++)
    {
        if (verbose)
        {
            cout << "Calculating distance starting at node " << trueRoute[i - 1] << " and going to node " << trueRoute[i] << endl;
        }
        Node currentNode = _nodes[trueRoute[i-1]];
        Node nextNode = _nodes[trueRoute[i]];
        dist += HelperFunctions::CalculateInterNodeDistance(currentNode, nextNode);
    }
    return dist;
}
References _nodes, and HelperFunctions::CalculateInterNodeDistance().
CanGetToNextCustomerSafely()
bool Vehicle::CanGetToNextCustomerSafely (const Node & from, const Node & to) const private
Checks to see if the Vehicle can safely go from one node to another with the battery cost and distance.
Safety is defined by the Vehicle going from the from node, to the to node, with enough battery left to go from the to node to a charging station. It doesn't necessarily mean the Vehicle MUST go to a charging station after getting to the to node, we just want to make sure that the Vehicle won't get stranded at the to node without enough battery to make it anywhere else.
Parameters
from The node the Vehicle starts at
to The node the Vehicle wants to go to
Returns
Whether or not the Vehicle can safely get from one node to the next.
{
    const int chargerIndex = GetClosestChargingStationToNode(to);
    if (chargerIndex == -1)
    {
        return false;
    }
    const Node closestCharger = _nodes[chargerIndex];
    if (currentBatteryCapacity > BatteryCost(from, to) + BatteryCost(to, closestCharger))
    {
        return true;
    }
    return false;
}
References _nodes, BatteryCost(), currentBatteryCapacity, and GetClosestChargingStationToNode().
GetClosestChargingStationToNode()
int Vehicle::GetClosestChargingStationToNode (const Node & node) const private
Helper for finding the closest charging station to the given node.
Parameters
node This is the node for which we are trying to find the nearest charging station
Returns
The index of the nearest charging station to the given node.
{
    float closest = numeric_limits<float>::max();
    int closestChargerIndex = -1;
    for (size_t i = 0; i < _nodes.size(); i++)
    {
        if (_nodes[i].isCharger && _nodes[i].index != node.index)
        {
            const float dist = HelperFunctions::CalculateInterNodeDistance(node, _nodes[i]);
            if (dist < closest)
            {
                closestChargerIndex = static_cast<int>(i);
                closest = dist;
            }
        }
    }
    return closestChargerIndex;
}
References _nodes, HelperFunctions::CalculateInterNodeDistance(), and Node::index.
ResetVehicle()
void Vehicle::ResetVehicle () inline
Resets the vehicle to the initial state using internal private parameters.
    {
        currentBatteryCapacity = _battery;
        maxBatteryCapacity = _battery;
        currentInventoryCapacity = _inventory;
        maxInventoryCapacity = _inventory;
        batteryConsumptionRate = _batteryRate;
    }
References _battery, _batteryRate, _inventory, batteryConsumptionRate, currentBatteryCapacity, currentInventoryCapacity, maxBatteryCapacity, and maxInventoryCapacity.
SimulateDrive()
float Vehicle::SimulateDrive (const vector< int > & desiredRoute, bool verbose = false)
Fitness calculation for the provided tour.
This function simulates the drive through the desired tour of customer nodes. Remember, the "solution" is defined by the preferred order of visiting each customer node. This desired route doesn't take into account any visits to the charging stations or the depot, so we need to artificially add those in. Since the EVRP gives us flexibility with when we visit these special nodes, and there is no requirement that we must visit these nodes, we don't include any visits to these nodes in the desired route.
This means that, since we don't know the true route once we start implementing constraints like fuel and capacity, we must find out the "true" route. We do that in this function. I'm positive that there's probably some graph theory or other math that I could do to make this function less messy and less confusing, but I don't have a better implementation at this time.
Parameters
desiredRoute The tour through just the customer nodes.
verbose This is false by default, and will hide a lot of the print outputs. This should not be set to true unless you want to output one specific route. In general, the outputting adds a lot of time to the simulation execution
Returns
Returns the true distance that the desired route would actually traverse with the fuel and capacity constraints
{
    //Resets the vehicle so that we are "starting fresh" every time a new drive starts
    ResetVehicle();
    if (verbose)
    {
        cout << "Simulating drive of route: ";
        HelperFunctions::PrintTour(desiredRoute);
    }
    //we will construct the "true" tour during the simulation. desiredRoute is just the order of customer nodes for this route.
    //we will need to find when we need to charge at a station and when we need to return to the depot as we "simulate" the drive.
    vector<int> paddedTour;
    //we start at the depot, which is always node "0"
    //starting at the depot satisfies part of the first constraint of the EVRP. We also need to end at the depot
    int currentNodeIndex = 0;
    paddedTour.push_back(currentNodeIndex);
    //start with zero distance
    float fullDistance = 0.f;
    //loop until we have serviced all customer nodes, which satisfies constraint number 2
    int customerNodesServiced = 0;
    while (static_cast<size_t>(customerNodesServiced) < desiredRoute.size())
    {
        if (verbose)
        {
            cout << "I can travel " << currentBatteryCapacity << " units and I have " << currentInventoryCapacity << " inventory remaining" << endl;
            cout << "Current Node Index: " << currentNodeIndex << endl;
        }
        /*
        This if statement checks for a supposed infinite loop. It is possible, under the current implementation, to have an impossible route
        where the vehicle must bounce between two charging stations, never having enough battery to safely go to the next customer.
        If that's the case, we want to heavily punish this route with a huge distance penalty.
        */
        if (paddedTour.size() > 10 &&
            (paddedTour[paddedTour.size() - 1] == paddedTour[paddedTour.size() - 3] && paddedTour[paddedTour.size() - 2] == paddedTour[paddedTour.size() - 4]))
        {
            //infinite loop of charging stations detected, break out and heavily penalize impossible route
            fullDistance += 1000000000.f;
            return fullDistance;
        }
        //We want to select the next customer node in the desired route to set as our preferred target
        int desiredRouteIndex = desiredRoute[customerNodesServiced];
        Node currentNode = _nodes[currentNodeIndex];
        Node nextDesiredNode = _nodes[desiredRouteIndex];
        //Calculate battery cost to go from the current node to the next desired node
        float routeCost = BatteryCost(currentNode, nextDesiredNode);
        const int demandCost = nextDesiredNode.demand;
        if (verbose)
        {
            cout << "Going from node (" << currentNode.x << ", " << currentNode.y << ") to node (" << nextDesiredNode.x << ", " << nextDesiredNode.y << ") will cost " << routeCost << " battery. This node has a demand of: " << demandCost << endl;
        }
        //we only want to go to the next customer node if we can get from where we are, to the next customer, then to a charging station.
        //If we can't go from the next customer to a charging station, we need to first visit a charging station or else we would get stranded
        //at the next customer. Bad day.
        const bool canGetToNextCustomerSafely = CanGetToNextCustomerSafely(currentNode, nextDesiredNode);
        if (canGetToNextCustomerSafely)
        {
            if (verbose)
            {
                cout << "I can go to this and have the battery to continue to the nearest node (aka I won't get stranded at this node)" << endl;
            }
            //Do we have the capacity to satisfy the demand at the next customer, and can we make the trip on our current battery state
            if (currentInventoryCapacity >= demandCost && currentBatteryCapacity > routeCost)
            {
                if (verbose)
                {
                    cout << "I went to this node!" << endl;
                }
                //travel to the next customer, subtracting the demand from our inventory and the battery cost from our battery capacity
                currentInventoryCapacity -= demandCost;
                currentBatteryCapacity -= routeCost;
                paddedTour.push_back(desiredRouteIndex);
                currentNodeIndex = desiredRouteIndex;
                customerNodesServiced++;
            }
            //we can't satisfy the next customer, either because we don't have enough battery to reach them or we don't have enough inventory
            else
            {
                //if we are lacking in inventory, we must visit the depot to restock.
                if (currentInventoryCapacity < demandCost)
                {
                    if (verbose)
                    {
                        cout << "I can't meet the demand at the next node, so I must go to the depot and restock." << endl;
                    }
                    //while we aren't at the depot, continue moving towards the depot.
                    while (currentNodeIndex != 0)
                    {
                        currentNode = _nodes[currentNodeIndex];
                        nextDesiredNode = _nodes[0];
                        routeCost = BatteryCost(currentNode, nextDesiredNode);
                        if (currentBatteryCapacity > routeCost)
{
                            //simulate driving cost
                            currentBatteryCapacity -= routeCost;
                            //restock inventory and recharge. one constant in the EVRP problem is there is always a charger at the depot
                            //if we introduced charging time/restock time/time windows for servicing, we wouldn't necessarily want to charge
                            //every time we went to the depot, because that might be unnecessary, but in the time-doesn't-matter version of this problem
                            //we might as well recharge when we restock
                            currentInventoryCapacity = maxInventoryCapacity;
                            currentBatteryCapacity = maxBatteryCapacity;
                            paddedTour.push_back(0);
                            currentNodeIndex = 0;
                        }
                        else
{
                            //visit the nearest charging station and continue moving towards the depot.
                            int chargingNodeIndex = GetClosestChargingStationToNode(currentNode);
                            currentBatteryCapacity = maxBatteryCapacity;
                            currentNodeIndex = chargingNodeIndex;
                            paddedTour.push_back(chargingNodeIndex);
                        }
                    }
                }
                else
                {
                    //should never reach this line of code
                    cout << "I am lost as a vehicle... how did I get here?" << endl;
                }
            }
        }
        //we can get to the next customer on our current battery, but once we get there we won't have enough battery to get anywhere else.
        //we must recharge before continuing safely.
        else
        {
            if (verbose)
            {
                cout << "I need to detour to a charging station before visiting this node." << endl;
            }
            //recharge the battery from the next charging station. This satisfies constraint 4, 5, 6, and 7.
            int chargingNodeIndex = GetClosestChargingStationToNode(currentNode);
            currentBatteryCapacity = maxBatteryCapacity;
            currentNodeIndex = chargingNodeIndex;
            paddedTour.push_back(chargingNodeIndex);
        }
        if (verbose)
        {
            cout << "----------------------------------------" << endl;
        }
    }
    //we exit the while loop when we are at the last desired customer node, but we need to simulate getting home, as required by constraint 1.
    //this is going to take the same structure as the loop we used above to get to the depot. I'm sure there's some clever way to just combine them
    //but....
    while (currentNodeIndex != 0)
    {
        const Node currentNode = _nodes[currentNodeIndex];
        const Node desiredNode = _nodes[0];
        const float routeCost = BatteryCost(currentNode, desiredNode);
        if (currentBatteryCapacity > routeCost)
        {
            currentBatteryCapacity -= routeCost;
            paddedTour.push_back(0);
            currentNodeIndex = 0;
        }
        else
        {
            int chargingNodeIndex = GetClosestChargingStationToNode(currentNode);
            currentBatteryCapacity = maxBatteryCapacity;
            currentNodeIndex = chargingNodeIndex;
            paddedTour.push_back(chargingNodeIndex);
        }
    }
    //we have now serviced every customer node and have driven back home, and constructed the true tour
    if (verbose)
    {
        cout << "True route: ";
        for (const auto i : paddedTour)
        {
            cout << i << " ";
        }
        cout << endl;
        cout << "----------------------------------------" << endl;
    }
    //the full distance is the "fitness" of this solution
    fullDistance = CalculateFullRouteDistance(paddedTour, false);
    return fullDistance;
}
References _nodes, BatteryCost(), CalculateFullRouteDistance(), CanGetToNextCustomerSafely(), currentBatteryCapacity, currentInventoryCapacity, Node::demand, GetClosestChargingStationToNode(), maxBatteryCapacity, maxInventoryCapacity, HelperFunctions::PrintTour(), ResetVehicle(), Node::x, and Node::y.
Member Data Documentation
_battery
float Vehicle::_battery private
An internal variable that holds the state of the maximum battery capacity
_batteryRate
float Vehicle::_batteryRate private
An internal variable that holds the state of the rate in which the battery discharges over distance
_inventory
int Vehicle::_inventory private
An internal variable that holds the state of the maximum vehicle inventory capacity
_nodes
vector<Node> Vehicle::_nodes private
All nodes in the EVRP graph
batteryConsumptionRate
float Vehicle::batteryConsumptionRate private
The battery consumption rate, shouldn't change during execution
currentBatteryCapacity
float Vehicle::currentBatteryCapacity private
The current battery capacity, updated during the simulation of the driving
currentInventoryCapacity
int Vehicle::currentInventoryCapacity private
The current inventory capacity, updated during the simulation of the driving
maxBatteryCapacity
float Vehicle::maxBatteryCapacity private
The maximum battery capacity, shouldn't change during execution
maxInventoryCapacity
int Vehicle::maxInventoryCapacity private
The maximum inventory capacity, shouldn't change during execution
The documentation for this class was generated from the following files:
EVRP/Vehicle.h
EVRP/Vehicle.cpp